### PR TITLE
fix credentials

### PR DESCRIPTION
**Pull request by trs-80**
Increasing flexibility in sending oauth credentials

### CODE REVIEW

**Comment by oalders** [comment]
I can push a fix for the failing Pod coverage tests. There are some uncovered methods, but we could allow that for now.

If you want a smaller diff, you don't need to include any boilerplate changes made by `Dist::Zilla` in the PR, since those just get created and committed when the dist gets released.

**Comment by trs-80** [comment]
I am fine with excluding the boilerplate changes - anything you could do to
shepherd this through would be greatly appreciated.

**Comment by oalders** [comment]
I've moved your changes into #10, but there's still a failing test that was introduced by the changes. Would you be able to have a look at it?

**Comment by oalders** [comment]
Sorry -- I should have force-pushed to a different branch. Having said that, this is ready for merge so I'll do that and release.

**Pull request merged**
